export const COURSES = [
  {
    id: 'full-stack-development',
    slug: 'full-stack-development',
    title: 'Full Stack Development',
    category: 'coding',
    duration: '14 Months',
    level: 'Intermediate',
    description: 'Become a complete developer — front to back, idea to launch. Master the skill of programming browsers, servers and databases with our experts while working on live projects.',
    imageUrl: 'https://images.unsplash.com/photo-1461749280684-dccba630e2f6?w=800&q=80&auto=format&fit=crop',
    featured: true,
    curriculum: [
      { title: 'HTML, CSS & JavaScript', topics: ['Semantic HTML5', 'CSS3 & Flexbox/Grid', 'ES6+ JavaScript', 'DOM Manipulation'] },
      { title: 'Frontend Frameworks', topics: ['React.js', 'Redux & State Management', 'Responsive Design', 'API Integration'] },
      { title: 'Backend Development', topics: ['Node.js & Express', 'RESTful APIs', 'Authentication & Security', 'Database Design'] },
      { title: 'Database & DevOps', topics: ['MongoDB', 'SQL Databases', 'Git & GitHub', 'Deployment & CI/CD'] },
    ],
    cities: ['ahmedabad-navrangpura', 'ahmedabad-bopal', 'ahmedabad-nikol', 'ahmedabad-vastral', 'ahmedabad-chandkheda', 'vadodara', 'rajkot-kalawad', 'rajkot-mavdi', 'rajkot-yagnik', 'gandhinagar', 'bhavnagar', 'jamnagar', 'junagadh', 'anand', 'navsari', 'bharuch', 'vapi', 'mehsana', 'morbi', 'surendranagar', 'surat-ak-road', 'surat-varachha', 'surat-katargam', 'surat-adajan'],
  },
  {
    id: 'ai-ml-data-science',
    slug: 'ai-ml-data-science',
    title: 'AI/ML & Data Science',
    category: 'ai-ml',
    duration: '16 Months',
    level: 'Advanced',
    description: 'Learn to use AI and Machine Learning to turn data into insights. Work with Python, visualization, and predictive models to prepare for careers in analytics and automation.',
    imageUrl: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=800&q=80&auto=format&fit=crop',
    featured: true,
    curriculum: [
      { title: 'Python Programming', topics: ['Python Fundamentals', 'NumPy & Pandas', 'Data Structures', 'OOP in Python'] },
      { title: 'Data Analysis', topics: ['Exploratory Data Analysis', 'Data Visualization', 'Statistical Methods', 'Feature Engineering'] },
      { title: 'Machine Learning', topics: ['Supervised Learning', 'Unsupervised Learning', 'Model Evaluation', 'Scikit-learn'] },
      { title: 'Deep Learning & AI', topics: ['Neural Networks', 'TensorFlow & Keras', 'NLP', 'Computer Vision'] },
    ],
    cities: ['ahmedabad-navrangpura', 'ahmedabad-bopal', 'ahmedabad-nikol', 'ahmedabad-vastral', 'ahmedabad-chandkheda', 'vadodara', 'rajkot-kalawad', 'rajkot-mavdi', 'rajkot-yagnik', 'gandhinagar', 'bhavnagar', 'jamnagar', 'junagadh', 'anand', 'navsari', 'bharuch', 'vapi', 'mehsana', 'morbi', 'surendranagar', 'surat-ak-road', 'surat-varachha', 'surat-adajan'],
  },
  {
    id: 'ui-ux-graphic-design',
    slug: 'ui-ux-graphic-design',
    title: 'UI/UX & Graphic Design',
    category: 'design',
    duration: '14 Months',
    level: 'Beginner',
    description: 'Master design skills that blend creativity with career success. Learn to design creative graphics and user-friendly digital experiences.',
    imageUrl: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=800&q=80&auto=format&fit=crop',
    featured: true,
    curriculum: [
      { title: 'Design Fundamentals', topics: ['Color Theory', 'Typography', 'Layout & Composition', 'Visual Hierarchy'] },
      { title: 'Graphic Design Tools', topics: ['Adobe Photoshop', 'Adobe Illustrator', 'CorelDRAW', 'Canva'] },
      { title: 'UI/UX Design', topics: ['User Research', 'Wireframing', 'Prototyping in Figma', 'Usability Testing'] },
      { title: 'Portfolio & Career', topics: ['Design Portfolio', 'Client Projects', 'Industry Trends', 'Freelancing'] },
    ],
    cities: ['ahmedabad-navrangpura', 'ahmedabad-bopal', 'ahmedabad-nikol', 'ahmedabad-vastral', 'ahmedabad-chandkheda', 'vadodara', 'rajkot-kalawad', 'rajkot-mavdi', 'rajkot-yagnik', 'gandhinagar', 'bhavnagar', 'jamnagar', 'junagadh', 'anand', 'navsari', 'bharuch', 'vapi', 'mehsana', 'morbi', 'surendranagar', 'surat-ak-road', 'surat-puna', 'surat-varachha', 'surat-katargam'],
  },
  {
    id: 'video-editing-3d-animation',
    slug: 'video-editing-3d-animation',
    title: 'Video Editing & 3D Animation',
    category: 'visualisation',
    duration: '14 Months',
    level: 'Intermediate',
    description: 'Create cinematic visuals and bring imagination to life. Train on industry tools like Maya and After Effects while building a portfolio.',
    imageUrl: 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=800&q=80&auto=format&fit=crop',
    featured: true,
    curriculum: [
      { title: 'Video Editing', topics: ['Adobe Premiere Pro', 'DaVinci Resolve', 'Color Grading', 'Sound Design'] },
      { title: '2D Animation', topics: ['After Effects', 'Motion Graphics', 'Character Animation', 'Keyframing'] },
      { title: '3D Modeling', topics: ['Autodesk Maya', 'Blender', '3D Texturing', 'Lighting & Rendering'] },
      { title: 'VFX & Compositing', topics: ['Green Screen', 'Particle Effects', 'Compositing', 'Showreel'] },
    ],
    cities: ['ahmedabad-navrangpura', 'ahmedabad-bopal', 'ahmedabad-nikol', 'ahmedabad-vastral', 'ahmedabad-chandkheda', 'vadodara', 'rajkot-kalawad', 'rajkot-mavdi', 'rajkot-yagnik', 'gandhinagar', 'bhavnagar', 'jamnagar', 'junagadh', 'anand', 'navsari', 'bharuch', 'vapi', 'mehsana', 'morbi', 'surendranagar', 'surat-ak-road', 'surat-varachha'],
  },
  {
    id: 'cyber-security',
    slug: 'cyber-security',
    title: 'Cyber Security',
    category: 'cyber-security',
    duration: '6 Months',
    level: 'Intermediate',
    description: 'Protect data, prevent threats, secure the future. Learn ethical hacking, network security, encryption, and incident response.',
    imageUrl: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=800&q=80&auto=format&fit=crop',
    featured: false,
    curriculum: [
      { title: 'Network Security', topics: ['TCP/IP', 'Firewalls', 'VPN', 'IDS/IPS'] },
      { title: 'Ethical Hacking', topics: ['Penetration Testing', 'Vulnerability Assessment', 'Kali Linux', 'Metasploit'] },
      { title: 'Cryptography', topics: ['Encryption Algorithms', 'PKI', 'SSL/TLS', 'Hashing'] },
      { title: 'Incident Response', topics: ['Forensics', 'Malware Analysis', 'Security Policies', 'Compliance'] },
    ],
    cities: ['ahmedabad-navrangpura', 'ahmedabad-bopal', 'ahmedabad-nikol', 'ahmedabad-vastral', 'ahmedabad-chandkheda', 'vadodara', 'rajkot-kalawad', 'rajkot-mavdi', 'rajkot-yagnik', 'gandhinagar', 'bhavnagar', 'jamnagar', 'junagadh', 'anand', 'navsari', 'bharuch', 'vapi', 'mehsana', 'morbi', 'surendranagar', 'surat-ak-road', 'surat-varachha'],
  },
  {
    id: 'web-frontend',
    slug: 'web-frontend',
    title: 'Web Front-End Development',
    category: 'coding',
    duration: '8 Months',
    level: 'Beginner',
    description: 'Design and code the face of modern websites.',
    imageUrl: 'https://images.unsplash.com/photo-1547658719-da2b51169166?w=800&q=80&auto=format&fit=crop',
    featured: false,
    curriculum: [
      { title: 'HTML & CSS', topics: ['HTML5', 'CSS3', 'Responsive Design', 'Sass/SCSS'] },
      { title: 'JavaScript', topics: ['ES6+', 'DOM', 'Async JS', 'APIs'] },
      { title: 'React.js', topics: ['Components', 'Hooks', 'Routing', 'State Management'] },
      { title: 'Tools & Deploy', topics: ['Git', 'Webpack/Vite', 'Testing', 'Deployment'] },
    ],
    cities: ['ahmedabad-navrangpura', 'ahmedabad-bopal', 'ahmedabad-nikol', 'ahmedabad-vastral', 'ahmedabad-chandkheda', 'vadodara', 'rajkot-kalawad', 'rajkot-mavdi', 'rajkot-yagnik', 'gandhinagar', 'bhavnagar', 'jamnagar', 'junagadh', 'anand', 'navsari', 'bharuch', 'vapi', 'mehsana', 'morbi', 'surendranagar', 'surat-ak-road', 'surat-varachha', 'surat-katargam'],
  },
  {
    id: 'web-backend',
    slug: 'web-backend',
    title: 'Web Back-End Development',
    category: 'coding',
    duration: '8 Months',
    level: 'Intermediate',
    description: 'Build the engine that powers every digital product.',
    imageUrl: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=800&q=80&auto=format&fit=crop',
    featured: false,
    curriculum: [
      { title: 'Server-Side Programming', topics: ['Node.js', 'Express.js', 'Python/Django', 'RESTful APIs'] },
      { title: 'Database', topics: ['MongoDB', 'MySQL', 'PostgreSQL', 'ORM'] },
      { title: 'Security & Auth', topics: ['JWT', 'OAuth', 'Rate Limiting', 'CORS'] },
      { title: 'DevOps', topics: ['Docker', 'CI/CD', 'Cloud Hosting', 'Monitoring'] },
    ],
    cities: ['ahmedabad-navrangpura', 'ahmedabad-bopal', 'ahmedabad-nikol', 'ahmedabad-vastral', 'ahmedabad-chandkheda', 'vadodara', 'rajkot-kalawad', 'rajkot-mavdi', 'rajkot-yagnik', 'gandhinagar', 'bhavnagar', 'jamnagar', 'junagadh', 'anand', 'navsari', 'bharuch', 'vapi', 'mehsana', 'morbi', 'surendranagar', 'surat-ak-road', 'surat-varachha'],
  },
  {
    id: 'data-analysis',
    slug: 'data-analysis',
    title: 'Data Analysis',
    category: 'ai-ml',
    duration: '6 Months',
    level: 'Beginner',
    description: 'Turn raw data into clear, actionable insights.',
    imageUrl: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80&auto=format&fit=crop',
    featured: false,
    curriculum: [
      { title: 'Excel & SQL', topics: ['Advanced Excel', 'SQL Queries', 'Data Cleaning', 'Pivot Tables'] },
      { title: 'Python for Analysis', topics: ['Pandas', 'NumPy', 'Matplotlib', 'Seaborn'] },
      { title: 'BI Tools', topics: ['Power BI', 'Tableau', 'Dashboard Design', 'KPI Tracking'] },
      { title: 'Statistics', topics: ['Descriptive Stats', 'Probability', 'Hypothesis Testing', 'Regression'] },
    ],
    cities: ['ahmedabad-navrangpura', 'ahmedabad-bopal', 'ahmedabad-nikol', 'ahmedabad-vastral', 'ahmedabad-chandkheda', 'vadodara', 'rajkot-kalawad', 'rajkot-mavdi', 'rajkot-yagnik', 'gandhinagar', 'bhavnagar', 'jamnagar', 'junagadh', 'anand', 'navsari', 'bharuch', 'vapi', 'mehsana', 'morbi', 'surendranagar', 'surat-ak-road', 'surat-adajan'],
  },
  {
    id: 'digital-marketing',
    slug: 'digital-marketing',
    title: 'Digital Marketing',
    category: 'short-term',
    duration: '3 Months',
    level: 'Beginner',
    description: 'Master SEO, social media, and online advertising with our Digital Marketing Course designed for real-world success.',
    imageUrl: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&q=80&auto=format&fit=crop',
    featured: true,
    curriculum: [
      { title: 'SEO & SEM', topics: ['On-page SEO', 'Off-page SEO', 'Google Ads', 'Keyword Research'] },
      { title: 'Social Media', topics: ['Facebook Marketing', 'Instagram Growth', 'LinkedIn Strategy', 'Content Calendar'] },
      { title: 'Analytics', topics: ['Google Analytics', 'UTM Tracking', 'Conversion Optimization', 'A/B Testing'] },
      { title: 'Email & Content', topics: ['Email Marketing', 'Content Strategy', 'Copywriting', 'Brand Building'] },
    ],
    cities: ['ahmedabad-navrangpura', 'ahmedabad-bopal', 'ahmedabad-nikol', 'ahmedabad-vastral', 'ahmedabad-chandkheda', 'vadodara', 'rajkot-kalawad', 'rajkot-mavdi', 'rajkot-yagnik', 'gandhinagar', 'bhavnagar', 'jamnagar', 'junagadh', 'anand', 'navsari', 'bharuch', 'vapi', 'mehsana', 'morbi', 'surendranagar', 'surat-ak-road', 'surat-puna', 'surat-varachha'],
  },
  {
    id: 'business-administration-commerce',
    slug: 'business-administration-commerce',
    title: 'Business Administration & Commerce',
    category: 'business',
    duration: '12 Months',
    level: 'Beginner',
    description: 'Expand your business and management skills through practical learning. Build skills in accounting, marketing, and operations.',
    imageUrl: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=800&q=80&auto=format&fit=crop',
    featured: false,
    curriculum: [
      { title: 'Business Fundamentals', topics: ['Management Principles', 'Business Communication', 'Economics', 'Entrepreneurship'] },
      { title: 'Finance & Accounting', topics: ['Financial Accounting', 'Cost Management', 'GST & Taxation', 'Tally Prime'] },
      { title: 'Marketing & Sales', topics: ['Marketing Strategy', 'Digital Marketing', 'Sales Management', 'CRM'] },
      { title: 'Operations', topics: ['Supply Chain', 'HR Management', 'Project Management', 'Business Law'] },
    ],
    cities: ['ahmedabad-navrangpura', 'ahmedabad-bopal', 'ahmedabad-nikol', 'ahmedabad-vastral', 'ahmedabad-chandkheda', 'vadodara', 'rajkot-kalawad', 'rajkot-mavdi', 'rajkot-yagnik', 'gandhinagar', 'bhavnagar', 'jamnagar', 'junagadh', 'anand', 'navsari', 'bharuch', 'vapi', 'mehsana', 'morbi', 'surendranagar', 'surat-ak-road', 'surat-katargam'],
  },
  {
    id: 'accounting-taxation',
    slug: 'accounting-taxation',
    title: 'Accounting & Taxation',
    category: 'business',
    duration: '6 Months',
    level: 'Beginner',
    description: 'Learn to manage financial records, prepare balance sheets, and handle taxation processes with practical tools.',
    imageUrl: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800&q=80&auto=format&fit=crop',
    featured: false,
    curriculum: [
      { title: 'Accounting Basics', topics: ['Journal Entries', 'Ledger', 'Trial Balance', 'Financial Statements'] },
      { title: 'Tally & Software', topics: ['Tally Prime', 'Tally ERP 9', 'QuickBooks', 'Excel'] },
      { title: 'Taxation', topics: ['GST', 'Income Tax', 'TDS', 'Tax Filing'] },
      { title: 'Practical Projects', topics: ['Company Accounts', 'Payroll', 'Audit Basics', 'Compliance'] },
    ],
    cities: ['ahmedabad-navrangpura', 'ahmedabad-bopal', 'ahmedabad-nikol', 'ahmedabad-vastral', 'ahmedabad-chandkheda', 'vadodara', 'rajkot-kalawad', 'rajkot-mavdi', 'rajkot-yagnik', 'gandhinagar', 'bhavnagar', 'jamnagar', 'junagadh', 'anand', 'navsari', 'bharuch', 'vapi', 'mehsana', 'morbi', 'surendranagar', 'surat-ak-road', 'surat-puna', 'surat-katargam'],
  },
  {
    id: 'careerx-ai',
    slug: 'careerx-ai',
    title: 'CareerX - AI',
    category: 'careerx-ai',
    duration: '16 Months',
    level: 'Beginner',
    description: 'CareerX - AI helps learners discover their true strengths and align them with future-ready skills through AI-driven assessments and insights.',
    imageUrl: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=800&q=80&auto=format&fit=crop',
    featured: false,
    curriculum: [
      { title: 'Self Assessment', topics: ['Aptitude Testing', 'Personality Profiling', 'Skill Mapping', 'Interest Analysis'] },
      { title: 'AI Foundations', topics: ['AI Concepts', 'Python Basics', 'Data Literacy', 'Tools & Platforms'] },
      { title: 'Career Planning', topics: ['Industry Exposure', 'Mentorship', 'Portfolio Building', 'Interview Prep'] },
      { title: 'Specialization', topics: ['Chosen Track Deep-Dive', 'Live Projects', 'Internship', 'Certification'] },
    ],
    cities: ['ahmedabad-navrangpura', 'ahmedabad-bopal', 'ahmedabad-nikol', 'ahmedabad-vastral', 'ahmedabad-chandkheda', 'vadodara', 'rajkot-kalawad', 'rajkot-mavdi', 'rajkot-yagnik', 'gandhinagar', 'bhavnagar', 'jamnagar', 'junagadh', 'anand', 'navsari', 'bharuch', 'vapi', 'mehsana', 'morbi', 'surendranagar', 'surat-ak-road'],
  },
  {
    id: 'python',
    slug: 'python',
    title: 'Python',
    category: 'coding',
    duration: '12 Months',
    level: 'Beginner',
    description: "Learn the world's most beginner-friendly programming language.",
    imageUrl: 'https://images.unsplash.com/photo-1526379095098-d400fd0bf935?w=800&q=80&auto=format&fit=crop',
    featured: false,
    curriculum: [
      { title: 'Python Basics', topics: ['Syntax', 'Data Types', 'Control Flow', 'Functions'] },
      { title: 'Advanced Python', topics: ['OOP', 'File Handling', 'Exception Handling', 'Modules'] },
      { title: 'Web & Automation', topics: ['Django/Flask', 'Web Scraping', 'APIs', 'Automation Scripts'] },
      { title: 'Data & AI Intro', topics: ['NumPy', 'Pandas', 'Matplotlib', 'ML Basics'] },
    ],
    cities: ['ahmedabad-navrangpura', 'ahmedabad-bopal', 'ahmedabad-nikol', 'ahmedabad-vastral', 'ahmedabad-chandkheda', 'vadodara', 'rajkot-kalawad', 'rajkot-mavdi', 'rajkot-yagnik', 'gandhinagar', 'bhavnagar', 'jamnagar', 'junagadh', 'anand', 'navsari', 'bharuch', 'vapi', 'mehsana', 'morbi', 'surendranagar', 'surat-ak-road', 'surat-varachha'],
  },
  {
    id: 'ui-ux-design',
    slug: 'ui-ux-design',
    title: 'UI/UX Design',
    category: 'design',
    duration: '5 Months',
    level: 'Beginner',
    description: 'Learn to design apps and websites people love to use.',
    imageUrl: 'https://images.unsplash.com/photo-1586717791821-3f44a563fa4c?w=800&q=80&auto=format&fit=crop',
    featured: false,
    curriculum: [
      { title: 'UX Research', topics: ['User Personas', 'Journey Mapping', 'Competitor Analysis', 'Surveys'] },
      { title: 'Wireframing', topics: ['Figma', 'Sketch', 'Low-Fi Wireframes', 'Hi-Fi Mockups'] },
      { title: 'Prototyping', topics: ['Interactive Prototypes', 'Micro-Interactions', 'Design Systems', 'Handoff'] },
      { title: 'Portfolio', topics: ['Case Studies', 'Presentation', 'Client Projects', 'Job Readiness'] },
    ],
    cities: ['ahmedabad-navrangpura', 'ahmedabad-bopal', 'ahmedabad-nikol', 'ahmedabad-vastral', 'ahmedabad-chandkheda', 'vadodara', 'rajkot-kalawad', 'rajkot-mavdi', 'rajkot-yagnik', 'gandhinagar', 'bhavnagar', 'jamnagar', 'junagadh', 'anand', 'navsari', 'bharuch', 'vapi', 'mehsana', 'morbi', 'surendranagar', 'surat-ak-road', 'surat-puna'],
  },
  {
    id: 'graphic-design',
    slug: 'graphic-design',
    title: 'Graphic Design',
    category: 'design',
    duration: '5 Months',
    level: 'Beginner',
    description: 'Turn your creativity into a profession with real-world design projects.',
    imageUrl: 'https://images.unsplash.com/photo-1626785774573-4b799315345d?w=800&q=80&auto=format&fit=crop',
    featured: false,
    curriculum: [
      { title: 'Design Theory', topics: ['Color Theory', 'Typography', 'Layout', 'Branding'] },
      { title: 'Adobe Suite', topics: ['Photoshop', 'Illustrator', 'InDesign', 'XD'] },
      { title: 'Projects', topics: ['Logo Design', 'Social Media', 'Print Design', 'Packaging'] },
      { title: 'Freelancing', topics: ['Client Management', 'Pricing', 'Portfolio', 'Networking'] },
    ],
    cities: ['ahmedabad-navrangpura', 'ahmedabad-bopal', 'ahmedabad-nikol', 'ahmedabad-vastral', 'ahmedabad-chandkheda', 'vadodara', 'rajkot-kalawad', 'rajkot-mavdi', 'rajkot-yagnik', 'gandhinagar', 'bhavnagar', 'jamnagar', 'junagadh', 'anand', 'navsari', 'bharuch', 'vapi', 'mehsana', 'morbi', 'surendranagar', 'surat-ak-road', 'surat-varachha', 'surat-katargam'],
  },
]
