export const MENTORS = [
  {
    id: 1,
    name: 'Mr. Ankit Dubey',
    role: 'Senior Designer at Google',
    type: 'Syllabus Mentor',
    subject: 'UI/UX',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&q=80&auto=format&fit=crop&crop=face',
  },
  {
    id: 2,
    name: 'Ms. Anwesha Kar',
    role: 'System Software Engineer',
    type: 'Syllabus Mentor',
    subject: 'DSA',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&q=80&auto=format&fit=crop&crop=face',
  },
  {
    id: 3,
    name: 'Mr. Alok Kumar',
    role: 'Director UX',
    type: 'Syllabus Mentor',
    subject: 'UI/UX',
    avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&q=80&auto=format&fit=crop&crop=face',
  },
  {
    id: 4,
    name: 'Mr. Piyush Jinjala',
    role: 'VFX Artist',
    type: 'Syllabus Mentor',
    subject: 'Animation',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&q=80&auto=format&fit=crop&crop=face',
  },
  {
    id: 5,
    name: 'Mr. Venu Madhav',
    role: 'Academician & Professor',
    type: 'Syllabus Mentor',
    subject: 'UI/UX',
    avatarUrl: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=400&q=80&auto=format&fit=crop&crop=face',
  },
  {
    id: 6,
    name: 'Mr. Sneh Mehta',
    role: 'Ex. ML Engineer @ TCS, Chief AI Officer @Miraiminds',
    type: 'Syllabus Mentor',
    subject: 'AI/ML',
    avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=400&q=80&auto=format&fit=crop&crop=face',
  },
  {
    id: 7,
    name: 'Mr. Jemish Lakhani',
    role: 'Founder & CEO',
    type: 'Syllabus Mentor',
    subject: 'Gaming',
    avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&q=80&auto=format&fit=crop&crop=face',
  },
  {
    id: 8,
    name: 'Mr. Akash Chaurasia',
    role: 'Lead Cloud Security Engineer @Zepto',
    type: 'Syllabus Mentor',
    subject: 'Cyber Security',
    avatarUrl: 'https://images.unsplash.com/photo-1531427186611-ecfd6d936c79?w=400&q=80&auto=format&fit=crop&crop=face',
  },
]
